version: '2'

services:
  nginx:
    build: ./nginx
    links:
      - app
    ports:
      - 8000:80
    networks:
      - backend
  node:
    build: ./nodejs
    networks:
      - backend

networks:
  backend:
