version: '2'

services:
  nginx:
    build: ./nginx
    links:
      - app
    ports:
      - 8000:80
    networks:
      - backend
  app:
    build: ./node_web_app
    volumes:
      - app_data:/usr/src/app
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  app_data:
    driver: local