version: '2'

services:
  nginx:
    build: ./nginx
    links:
      - app
    ports:
      - 8000:80
    networks:
      - backend
  app:
    build: ./nodejs
    volumes:
      - ./app:/src/app
    depends_on: 
      - nginx
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  app_data:
    driver: local